### PR TITLE
Added several configuration stuff

### PR DESCRIPTION
**Pull request by SapitoSucio**
This PR adds various theme settings. The new theme settings include custom fonts (Roboto for text and Roboto Mono for code), a favicon, and a logo. The color palette has also been updated with light blue as the primary color and teal as the accent color.

Additional theme features have been added such as content code annotation, content code copy, content tabs link, content tooltips, navigation footer, navigation indexes, navigation instant, navigation top, navigation tracking, search highlight, search share, search suggest, and toc follow. 

Markdown extensions have also been added including abbr, admonition, attr_list, def_list, footnotes, md_in_html, toc with permalink enabled. Pymdownx extensions have also been added such as arithmatex with generic enabled, betterem with smart_enable set to all, caret, details, emoji with emoji_generator set to materialx.emoji.to_svg and emoji_index set to materialx.emoji.twemoji. Pymdownx highlight has also been added with anchor_linenums enabled and line_spans set to __span. Other pymdownx extensions include inlinehilite, keys, mark, superfences with custom fences for mermaid.

So we now basically have things like this:

https://github.com/rathena/user-guides/assets/7357354/e29324f8-76d8-4b5a-819f-666ca936f2ee

and this 

https://github.com/rathena/user-guides/assets/7357354/6d514cc8-7809-4ebe-b473-dd05f2626fdd

and this

image

and this

https://github.com/rathena/user-guides/assets/7357354/b8ed761f-82fa-4f24-9817-fc5d3ad250d2

# You can see it live here with some examples https://sapitosucio.github.io/froggo-guides/

### CODE REVIEW

**Comment by Akkarinage** [comment]
Perhaps example usage of these new fandangled features can be typed up into [CONTRIBUTING.md](https://github.com/rathena/user-guides/blob/master/CONTRIBUTING.md) 

I'm not a fan of the logo's overlay.

**Comment by SapitoSucio** [comment]
> Perhaps example usage of these new fandangled features can be typed up into [CONTRIBUTING.md](https://github.com/rathena/user-guides/blob/master/CONTRIBUTING.md)
> 
> I'm not a fan of the logo's overlay.


I can put some examples on the CONTRIBUGINT.md 😊

About the logo, I could remove the book icon and just leave it like rA, what do u say ?

**Comment by Akkarinage** [comment]
> I can put some examples on the CONTRIBUGINT.md 😊

Thank you :) 

 
> About the logo, I could remove the book icon and just leave it like rA, what do u say ?

Yes please.

Also just noticed, if we're going to change the colour of the nav bar, we might as well use the "rA Blue" `#416e98`

**Comment by Akkarinage** [comment]
Looking good! Are you all done with changes?

**Review by Akkarinage — APPROVED** [review]

**Comment by SapitoSucio** [comment]
I think yes, I'm trying to improve the highlight syntax of C++ and bash commands, but I think I could open up a new PR when I get to that part 🐸

**Review by aleos89 — APPROVED** [review]

**Pull request merged**
